// Mirrored from unison/src/utils/errors.ts. Keep in sync manually when new
// codes ship server-side.

export const UnisonErrorCode = {
  INVALID_PAYLOAD: "INVALID_PAYLOAD",
  SONG_TOO_LONG: "SONG_TOO_LONG",
  ARTIST_TOO_LONG: "ARTIST_TOO_LONG",
  PAYLOAD_TOO_LARGE: "PAYLOAD_TOO_LARGE",
  INVALID_DURATION: "INVALID_DURATION",
  TTML_MALFORMED: "TTML_MALFORMED",
  TTML_FORMATTED: "TTML_FORMATTED",
  RATE_LIMITED: "RATE_LIMITED",
  VARIANT_CAP_REACHED: "VARIANT_CAP_REACHED",
  AUTH_REQUIRED: "AUTH_REQUIRED",
  INVALID_ID: "INVALID_ID",
  NOT_OWNER: "NOT_OWNER",
  NOT_FOUND: "NOT_FOUND",
  MISSING_QUERY: "MISSING_QUERY",
  INVALID_SIGNED_BODY: "INVALID_SIGNED_BODY",
  TIMESTAMP_EXPIRED: "TIMESTAMP_EXPIRED",
  NONCE_REPLAY: "NONCE_REPLAY",
  PUBLIC_KEY_REQUIRED: "PUBLIC_KEY_REQUIRED",
  KEY_ID_MISMATCH: "KEY_ID_MISMATCH",
  INVALID_SIGNATURE: "INVALID_SIGNATURE",
  INVALID_VOTE: "INVALID_VOTE",
  INVALID_REPORT_REASON: "INVALID_REPORT_REASON",
  REPORT_DETAILS_TOO_LONG: "REPORT_DETAILS_TOO_LONG",
} as const;

export type UnisonErrorCode = (typeof UnisonErrorCode)[keyof typeof UnisonErrorCode];
